name = "advent_of_code"
description = "Advent of Code - SPARK-verified puzzle solutions"
version = "0.1.0-dev"
authors = ["Heziode"]
maintainers = ["Heziode <heziode@users.noreply.github.com>"]
maintainers-logins = ["Heziode"]
licenses = "MIT"
website = "https://github.com/Heziode/Advent_Of_Code"
tags = ["advent-of-code", "spark", "puzzles"]

[build-switches]
"*".style_checks = ["-gnatyy", "-gnatyM120", "-gnatw.X"]
"*".ada_version = ["-gnat2022"]

[[depends-on]]
gnat = ">=12"

[[depends-on]]
resources = "~0.1.0"

[[depends-on]]
gnatprove = "^15.1.0"
